#!/bin/bash
PROJDIR="/home/jb55/kouyou"
PIDFILE="$PROJDIR/kouyou.pid"
SPAREPROC=1
MAXCHILD=1

cd $PROJDIR
if [ -f $PIDFILE ]; then
   kill `cat -- $PIDFILE`
   rm -f -- $PIDFILE
fi
exec python ./manage.py runfcgi maxspare=$SPAREPROC maxchildren=$MAXCHILD host=127.0.0.1 port=9098 pidfile=$PIDFILE --settings=settings

